#### 이자율 변수와 loan_grade 간 N집단 평균 차이 검정

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("./credit_risk_dataset.csv") 
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [3]:
df = df[['loan_int_rate', 'loan_grade']]

In [4]:
df.head()

   loan_int_rate loan_grade
0          16.02          D
1          11.14          B
2          12.87          C
3          15.23          C
4          14.27          C

In [5]:
df = df.dropna(axis=0)

In [6]:
df.loan_grade.value_counts()

loan_grade
A    9774
B    9395
C    5828
D    3314
E     881
F     214
G      59
Name: count, dtype: int64

In [15]:
df_a = df[df['loan_grade'] == 'A']['loan_int_rate']
df_b = df[df['loan_grade'] == 'B']['loan_int_rate']
df_c = df[df['loan_grade'] == 'C']['loan_int_rate']
df_d = df[df['loan_grade'] == 'D']['loan_int_rate']
df_e = df[df['loan_grade'] == 'E']['loan_int_rate']
df_f = df[df['loan_grade'] == 'F']['loan_int_rate']
df_g = df[df['loan_grade'] == 'G']['loan_int_rate']

In [16]:
df_a

5        7.14
8        8.90
11       8.63
12       7.90
14       7.90
         ...
32565    8.90
32567    7.74
32572    8.49
32573    6.17
32577    7.49
Name: loan_int_rate, Length: 9774, dtype: float64

#### 정규성 검정 - 샤피로 윌크 테스트

In [17]:
import scipy as sp

In [18]:
test_stat, p = sp.stats.shapiro(df_a)  
print("검정통계량: {}, p-value: {}".format(test_stat, p)) 
print("귀무가설 기각. 정규분포를 따르지 않는다.")

검정통계량: 0.972303569316864, p-value: 1.1420708601109048e-39
귀무가설 기각. 정규분포를 따르지 않는다.

In [19]:
p < 0.05

True

#### Kruskal-Wallis 테스트

In [20]:
test_stat, p_val = sp.stats.kruskal(df_a, df_b, df_c, df_d, df_e, df_f, df_g)  
print("검정통계량: {}, p-value: {}".format(test_stat, p_val))  
print("귀무가설 기각. 집단 간 평균에 차이가 있다.")

검정통계량: 26447.62535693569, p-value: 0.0
귀무가설 기각. 집단 간 평균에 차이가 있다.

In [21]:
p_val < 0.05

True