### 이자율 변수와 loan_grade 간 N집단 평균 차이 검정 및 두 집단 간 평균 차이 검정

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("./credit_risk_dataset.csv") 
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [4]:
df = df[['loan_int_rate', 'loan_grade']]

In [5]:
df.head()

   loan_int_rate loan_grade
0          16.02          D
1          11.14          B
2          12.87          C
3          15.23          C
4          14.27          C

In [6]:
df = df.dropna(axis=0)

In [7]:
df.loan_grade.value_counts()

loan_grade
A    9774
B    9395
C    5828
D    3314
E     881
F     214
G      59
Name: count, dtype: int64

In [8]:
df_a = df[df['loan_grade'] == 'A']['loan_int_rate']
df_b = df[df['loan_grade'] == 'B']['loan_int_rate']
df_c = df[df['loan_grade'] == 'C']['loan_int_rate']
df_d = df[df['loan_grade'] == 'D']['loan_int_rate']
df_e = df[df['loan_grade'] == 'E']['loan_int_rate']
df_f = df[df['loan_grade'] == 'F']['loan_int_rate']
df_g = df[df['loan_grade'] == 'G']['loan_int_rate']

In [9]:
df_a

5        7.14
8        8.90
11       8.63
12       7.90
14       7.90
         ...
32565    8.90
32567    7.74
32572    8.49
32573    6.17
32577    7.49
Name: loan_int_rate, Length: 9774, dtype: float64

## N 집단 평균 차이 검정

#### 정규성 검정 - 샤피로 윌크 테스트

In [10]:
import scipy as sp

In [11]:
test_stat, p = sp.stats.shapiro(df_a)  
print("검정통계량: {}, p-value: {}".format(test_stat, p)) 
print("귀무가설 기각. 정규분포를 따르지 않는다.")

검정통계량: 0.9723324953639928, p-value: 1.184937933157825e-39
귀무가설 기각. 정규분포를 따르지 않는다.

In [12]:
p < 0.05

np.True_

#### Kruskal-Wallis 테스트

In [13]:
test_stat, p_val = sp.stats.kruskal(df_a, df_b, df_c, df_d, df_e, df_f, df_g)  
print("검정통계량: {}, p-value: {}".format(test_stat, p_val))  
print("귀무가설 기각. 집단 간 평균에 차이가 있다.")

검정통계량: 26447.62535693569, p-value: 0.0
귀무가설 기각. 집단 간 평균에 차이가 있다.

In [16]:
print(p_val < 0.05)

True

## 두 집단 간 평균 차이 검정

In [19]:
df['loan_grade'].unique()

array(['D', 'B', 'C', 'A', 'E', 'F', 'G'], dtype=object)

- 7C2번의 평균 차이 검정을 해야함

#### 정규성 검정

In [25]:
import scipy as sp
test_stat, p = sp.stats.shapiro(df_a)
print("검정통계량: {}, p-value: {}".format(test_stat, p))
print("귀무가설 기각. 집단 A는 정규분포를 따르지 않는다. ")

검정통계량: 0.9723324953639928, p-value: 1.184937933157825e-39
귀무가설 기각. 집단 A는 정규분포를 따르지 않는다.

In [28]:
import scipy as sp
test_stat, p = sp.stats.shapiro(df_b)
print("검정통계량: {}, p-value: {}".format(test_stat, p))
print("귀무가설 기각. 집단 B는 정규분포를 따르지 않는다. ")

검정통계량: 0.9790712242582573, p-value: 6.291264503704206e-35
귀무가설 기각. 집단 B는 정규분포를 따르지 않는다.

In [29]:
import scipy as sp
test_stat, p = sp.stats.shapiro(df_c)
print("검정통계량: {}, p-value: {}".format(test_stat, p))
print("귀무가설 기각. 집단 C는 정규분포를 따르지 않는다. ")

검정통계량: 0.9672836336911697, p-value: 1.9583392094582143e-34
귀무가설 기각. 집단 C는 정규분포를 따르지 않는다.

In [31]:
import scipy as sp
test_stat, p = sp.stats.shapiro(df_d)
print("검정통계량: {}, p-value: {}".format(test_stat, p))
print("귀무가설 기각. 집단 d는 정규분포를 따르지 않는다. ")

검정통계량: 0.9715650378980352, p-value: 3.745217106141961e-25
귀무가설 기각. 집단 d는 정규분포를 따르지 않는다.

In [33]:
import scipy as sp
test_stat, p = sp.stats.shapiro(df_e)
print("검정통계량: {}, p-value: {}".format(test_stat, p))
print("귀무가설 기각. 집단 e는 정규분포를 따르지 않는다. ")

검정통계량: 0.9505084011592572, p-value: 1.279164696220979e-16
귀무가설 기각. 집단 e는 정규분포를 따르지 않는다.

In [35]:
import scipy as sp
test_stat, p = sp.stats.shapiro(df_f)
print("검정통계량: {}, p-value: {}".format(test_stat, p))
print("귀무가설 기각. 집단 f는 정규분포를 따르지 않는다. ")

검정통계량: 0.9656164591111799, p-value: 4.596094011910491e-05
귀무가설 기각. 집단 f는 정규분포를 따르지 않는다.

In [38]:
import scipy as sp
test_stat, p = sp.stats.shapiro(df_g)
print("검정통계량: {}, p-value: {}".format(test_stat, p))
print("귀무가설 기각하지 않는다. 집단 f는 정규분포를 따른다. ")

검정통계량: 0.9707979664111377, p-value: 0.1670155754088532
귀무가설 기각하지 않는다. 집단 f는 정규분포를 따른다.

In [40]:
print("집단 f 빼고 다 정규분포를 따르지 않기 때문에, rank-sum test 해야함 ")
print("7C2는 21번임.")

집단 f 빼고 다 정규분포를 따르지 않기 때문에, rank-sum test 해야함
7C2는 21번임.

In [42]:
df_list = [df_a, df_b, df_c, df_d, df_e, df_f, df_g]
grade_list = ['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [57]:
h1_counts = 0

for idx_i, grade_i in enumerate(grade_list):
    for idx_j, grade_j in enumerate(grade_list):
        if idx_i < idx_j:
            if np.mean(df_list[idx_i]) >= np.mean(df_list[idx_j]):
                test_stat, p = sp.stats.ranksums(df_list[idx_i], df_list[idx_j], alternative='greater')
                print("{},{}: 검정통계량: {}, p-value: {}".format(grade_i, grade_j, test_stat, p))
                if p < 0.05: h1_counts = h1_counts+1
            else:
                test_stat, p = sp.stats.ranksums(df_list[idx_i], df_list[idx_j], alternative='less')
                print("{},{}: 검정통계량: {}, p-value: {}".format(grade_i, grade_j, test_stat, p))
                if p < 0.05: h1_counts = h1_counts+1

a,b: 검정통계량: -119.08767196051478, p-value: 0.0
a,c: 검정통계량: -104.56031201785842, p-value: 0.0
a,d: 검정통계량: -86.07314112587375, p-value: 0.0
a,e: 검정통계량: -49.14018884753516, p-value: 0.0
a,f: 검정통계량: -25.06355521429428, p-value: 6.2120377720866836e-139
a,g: 검정통계량: -13.263486465306745, p-value: 1.884773965027231e-40
b,c: 검정통계량: -97.77273237256222, p-value: 0.0
b,d: 검정통계량: -85.35884874990268, p-value: 0.0
b,e: 검정통계량: -49.04299962297699, p-value: 0.0
b,f: 검정통계량: -25.052681226338066, p-value: 8.161298129998766e-139
b,g: 검정통계량: -13.261854499652864, p-value: 1.9262475054065683e-40
c,d: 검정통계량: -65.21469490811866, p-value: 0.0
c,e: 검정통계량: -46.71312589014813, p-value: 0.0
c,f: 검정통계량: -24.815105703663527, p-value: 3.0796889829669823e-136
c,g: 검정통계량: -13.2361751092126, p-value: 2.712083528388632e-40
d,e: 검정통계량: -31.666520610674034, p-value: 2.246252734978186e-220
d,f: 검정통계량: -22.85714149946058, p-value: 6.2046865097684e-116
d,g: 검정통계량: -13.165753863608337, p-value: 6.9075882860902845e-40
e,f: 검정통계량: -13.679047118129402, p-value: 6.772806164719774e-43
e,g: 검정통계량: -12.155783457583249, p-value: 2.672346953096972e-34
f,g: 검정통계량: -8.050399840253005, p-value: 4.126199330179136e-16

In [58]:
h1_counts

21

In [59]:
print("21번 모두 p-value가 0.05보다 작아 귀무가설을 기각, Grade간의 중앙값은 차이가 있다. ")

21번 모두 p-value가 0.05보다 작아 귀무가설을 기각, Grade간의 중앙값은 차이가 있다.