#### 가설검정_코드복습

#### 두 집단 평균 차이 검정

In [2]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv("./performance.csv")
df.head()

   GENDER TEAM           EDUCATION   TRAINING  ACHIEVEMENT  ABILITY  ATTITUDE
0  female    B   bachelor's degree       none           72       72        74
1  female    C        some college  completed           69       90        88
2  female    B     master's degree       none           90       95        93
3    male    A  associate's degree       none           47       57        44
4    male    C        some college       none           76       78        75

In [4]:
df['TEAM'].unique()

array(['B', 'C', 'A', 'D', 'E'], dtype=object)

In [5]:
df_a = df[df['TEAM'] == 'A']
df_b = df[df['TEAM'] == 'B']
df_c = df[df['TEAM'] == 'C']
df_d = df[df['TEAM'] == 'D']
df_e = df[df['TEAM'] == 'E']

In [6]:
df_a_ach = df_a['ACHIEVEMENT']
df_b_ach = df_b['ACHIEVEMENT']
df_c_ach = df_c['ACHIEVEMENT']
df_d_ach = df_d['ACHIEVEMENT']
df_e_ach = df_e['ACHIEVEMENT']

In [7]:
# 가설설정 
print("H0: 팀A와 팀B의 평균 성과 점수는 차이가 없다.")
print("H1: 팀B의 성과점수가 팀A의 성과점수보다 크다. ")

H0: 팀A와 팀B의 평균 성과 점수는 차이가 없다.
H1: 팀B의 성과점수가 팀A의 성과점수보다 크다.

In [10]:
# 정규성검정 (샤피로 윌크 검정)
import scipy as sp
test_stat, p = sp.stats.shapiro(df_a_ach)
print("H0: 정규 분포를 따른다. ")
print("H1: 정규 분포를 따르지 않는다.")
print("검정통계량: {}, p-value: {}".format(test_stat, p))
print("귀무가설 기각할 수 없음, 정규분포를 따른다. ")

H0: 정규 분포를 따른다.
H1: 정규 분포를 따르지 않는다.
검정통계량: 0.9917360440600248, p-value: 0.8545319451007725
귀무가설 기각할 수 없음, 정규분포를 따른다.

In [12]:
test_stat, p = sp.stats.shapiro(df_b_ach)
print("H0: 정규 분포를 따른다. ")
print("H1: 정규 분포를 따르지 않는다.")
print("검정통계량: {}, p-value: {}".format(test_stat, p))
print("귀무가설 기각, 정규분포를 따르지 않는다. ")

H0: 정규 분포를 따른다.
H1: 정규 분포를 따르지 않는다.
검정통계량: 0.9808056990812756, p-value: 0.01038942653443885
귀무가설 기각, 정규분포를 따르지 않는다.

In [13]:
# z-test 
df_a_mean = np.mean(df_a_ach)
df_b_mean = np.mean(df_b_ach)
print(df_a_mean)
print(df_b_mean)

61.62921348314607
63.45263157894737

In [19]:
df_a_var = df_a_ach.var(ddof=0)
df_b_var = df_b_ach.var(ddof=0)
print(df_a_var)
print(df_b_var)

208.54791061734628
238.00565096952909

In [21]:
len_a = len(df_a_ach)
len_b = len(df_b_ach)
print(len_a)
print(len_b)

89
190

In [22]:
z_value = (df_b_mean - df_a_mean)/((df_a_var/len_a) + (df_b_var/len_b))**0.5
print(z_value)

0.9615739353898897

In [27]:
z_dist = sp.stats.norm(0, 1)
p_value = 1-z_dist.cdf(z_value)
print(p_value)

0.16813183477339466

In [28]:
print("H0: 두 평균의 차이가 없다.")
print("H1: 두 평균의 차이가 있다. ")
print("H0 기각할 수 없다. 두 평균의 차이가 없다. ")

H0: 두 평균의 차이가 없다.
H1: 두 평균의 차이가 있다.
H0 기각할 수 없다. 두 평균의 차이가 없다.

In [31]:
# t-test
test_stats, p = sp.stats.ttest_ind(df_b_ach, df_a_ach, alternative='greater')
print("검정통계량: {}, p-value: {}".format(test_stat, p))

검정통계량: 0.9808056990812756, p-value: 0.17517079808299785

In [33]:
# ranksum tset 
test_stats, p = sp.stats.ranksums(df_b_ach, df_a_ach, alternative='greater')
print("검정통계량: {}, p-value: {}".format(test_stat, p))

검정통계량: 0.9808056990812756, p-value: 0.08787044816326

#### 세 집단의 평균 비교

In [37]:
print("H0: 팀A, 팀B, 팀C, 팀D, 팀E의 평균 성과 점수는 차이가 없다.")
print("H1: 팀A, 팀B, 팀C, 팀D, 팀E의 평균 성과 점수는 차이가 있다.")

H0: 팀A, 팀B, 팀C, 팀D, 팀E의 평균 성과 점수는 차이가 없다.
H1: 팀A, 팀B, 팀C, 팀D, 팀E의 평균 성과 점수는 차이가 있다.

In [34]:
# 정규성 검정 (shapiro)

In [36]:
# 등분산성 검정 
print("H0: 팀 A,B,C,D,E의 분산이 동일하다. ")
print("H1: 팀 A,B,C,D,E의 분산이 동일하지 않다. ")
test_stat, p = sp.stats.bartlett(df_a_ach, df_b_ach, df_c_ach, df_d_ach, df_e_ach)
print("검정통계량: {}, p-value: {}".format(test_stat, p))
print("귀무가설 기각할 수 없음, 분산이 동일하다. ")

H0: 팀 A,B,C,D,E의 분산이 동일하다.
H1: 팀 A,B,C,D,E의 분산이 동일하지 않다.
검정통계량: 4.075678014368108, p-value: 0.39586081869788264
귀무가설 기각할 수 없음, 분산이 동일하다.

In [39]:
# ANOVA 
test_stat, p = sp.stats.f_oneway(df_a_ach, df_b_ach, df_c_ach, df_d_ach, df_e_ach)
print("검정통계량: {}, p-value: {}".format(test_stat, p))
print("귀무가설 기각, 평균 성과 점수에 차이가 있다.")

검정통계량: 14.593885166332635, p-value: 1.3732194030370688e-11
귀무가설 기각, 평균 성과 점수에 차이가 있다.

In [41]:
# kruskal
test_stat, p = sp.stats.kruskal(df_a_ach, df_b_ach, df_c_ach, df_d_ach, df_e_ach)
print("검정통계량: {}, p-value: {}".format(test_stat, p))
print("귀무가설 기각, 성과 점수 중앙값에 차이가 있다.")

검정통계량: 57.079329705742886, p-value: 1.1906568165839682e-11
귀무가설 기각, 평균 성과 점수에 차이가 있다.

#### 연관성 검정 - 카이제곱 검정

In [42]:
print("H0: 팀C여부와 사내 수강 여부에는 연관성이 없다. ")
print("H1: 팀C여부와 사내수강 여부에는 연관성이 있다.")

H0: 팀C여부와 사내 수강 여부에는 연관성이 없다.
H1: 팀C여부와 사내수강 여부에는 연관성이 있다.

In [43]:
df['C_OR_NOT'] = np.where(df['TEAM']=='C', 'C', 'not_C')
df.head()

,GENDER,TEAM,EDUCATION,TRAINING,ACHIEVEMENT,ABILITY,ATTITUDE,C_OR_NOT
0,female,B,bachelor's degree,none,72,72,74,not_C
1,female,C,some college,completed,69,90,88,C
2,female,B,master's degree,none,90,95,93,not_C
3,male,A,associate's degree,none,47,57,44,not_C
4,male,C,some college,none,76,78,75,C

In [44]:
df['TRAINING'].unique()

array(['none', 'completed'], dtype=object)

In [45]:
df['C_OR_NOT'].unique()

array(['not_C', 'C'], dtype=object)

In [46]:
obs = pd.crosstab(df['C_OR_NOT'], df['TRAINING'])
obs

TRAINING  completed  none
C_OR_NOT
C               117   202
not_C           241   440

In [49]:
test_stat, p, d, expected = sp.stats.chi2_contingency(obs)
print("검정통계량: {}, p-value: {}".format(test_stat, p)) 
print("H0 기각할 수 없음, 연관성이 없다.")

검정통계량: 0.10576554193252763, p-value: 0.745017489209715
H0 기각할 수 없음, 연관성이 없다.