## 앙상블학습_랜덤포레스트분류회귀

In [1]:
import pandas as pd
df = pd.read_csv('wine_data.csv')
df

,Alcohol,Malic,Ash,Alcalinity,Magesium,Phenols,Flavanoids,Nonflavanoids,Proanthocyanins,Color,Hue,Dilution,Proline,class
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,0
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,0
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,0
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,0
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,2
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,2
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,2
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,2
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,2

In [2]:
features = ['Alcohol', 'Malic', 'Ash', 'Alcalinity', 'Magesium', 'Phenols',
       'Flavanoids', 'Nonflavanoids', 'Proanthocyanins', 'Color', 'Hue',
       'Dilution', 'Proline']

X = df[features]
y = df['class']

In [3]:
# 트레이닝/테스트 데이터 분할
from sklearn.model_selection import train_test_split
X_tn, X_te, y_tn, y_te = train_test_split(X, y, random_state=0)

In [11]:
# 데이터 표준화
from sklearn.preprocessing import StandardScaler
std_scale = StandardScaler()
std_scale.fit(X_tn)
X_tn_std = std_scale.transform(X_tn)
X_te_std = std_scale.transform(X_te)

In [12]:
# 랜덤포레스트 분류
from sklearn.ensemble import RandomForestClassifier
clf_rf = RandomForestClassifier(max_depth=2, random_state=0)
clf_rf.fit(X_tn_std, y_tn)

RandomForestClassifier(max_depth=2, random_state=0)

In [13]:
# 예측
pred_rf = clf_rf.predict(X_te_std)
print(pred_rf)

[0 2 1 0 1 1 0 2 1 1 2 2 0 1 2 1 0 0 2 0 0 0 0 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 0 0 1 1 1]

In [14]:
# 정확도
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_te, pred_rf)
print(accuracy)

0.9555555555555556

In [15]:
# 정밀도 (precision)
from sklearn.metrics import precision_score
precision = precision_score(y_te, pred_rf, average='macro')
print(precision)

0.943355119825708

In [16]:
# 리콜
from sklearn.metrics import recall_score
recall = recall_score(y_te, pred_rf, average='macro')
print(recall)

0.9682539682539683

In [17]:
# f1 스코어
from sklearn.metrics import f1_score
f1 = f1_score(y_te, pred_rf, average='macro')
print(f1)

0.9536244800950683

In [18]:
# confusion matrix 확인 
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_te, pred_rf)
print(conf_matrix)

[[16  0  0]
 [ 1 19  1]
 [ 0  0  8]]

In [19]:
# 분류 레포트 확인
from sklearn.metrics import classification_report
class_report = classification_report(y_te, pred_rf)
print(class_report)

              precision    recall  f1-score   support

           0       0.94      1.00      0.97        16
           1       1.00      0.90      0.95        21
           2       0.89      1.00      0.94         8

    accuracy                           0.96        45
   macro avg       0.94      0.97      0.95        45
weighted avg       0.96      0.96      0.96        45

## 랜덤포레스트 회귀

In [20]:
df = pd.read_csv('house_prices.csv')
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [21]:
features = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT']

X = df[features]
y = df['MEDV']

In [22]:
# 트레이닝/테스트 데이터 분할
from sklearn.model_selection import train_test_split
X_tn, X_te, y_tn, y_te = train_test_split(X, y, random_state=0)

In [23]:
# 데이터 표준화
from sklearn.preprocessing import StandardScaler
std_scale = StandardScaler()
std_scale.fit(X_tn)
X_tn_std = std_scale.transform(X_tn)
X_te_std = std_scale.transform(X_te)

In [25]:
# 랜덤포레스트회귀 학습 
from sklearn.ensemble import RandomForestRegressor

clf_rf = RandomForestRegressor(max_depth=2, random_state=0)
clf_rf.fit(X_tn_std, y_tn)

RandomForestRegressor(max_depth=2, random_state=0)

In [26]:
# 예측
rf_pred = clf_rf.predict(X_te_std)
print(rf_pred)

[25.13026738 22.45503023 21.72597661 14.02746048 21.72597661 23.39001805
 21.72597661 23.25907479 21.72597661 21.72597661 14.02746048 14.64220662
 15.06631268 14.02746048 43.87712974 31.67863592 21.65508147 32.81235452
 25.29273146 23.32331968 25.13026738 21.72597661 21.72597661 25.13026738
 21.72597661 20.30936428 21.72597661 15.44912052 43.05952486 15.44407281
 14.67676803 17.77333379 21.78263112 21.72597661 23.25907479 17.82865762
 14.02746048 22.58953053 14.47304952 15.1343252  23.39001805 21.72597661
 23.25907479 14.67676803 23.46698736 23.25907479 16.09842807 15.6439473
 14.79476526 23.65611834 16.17750951 15.44407281 21.72597661 43.73480054
 15.44407281 16.09842807 21.72597661 21.72597661 20.36601879 15.44407281
 24.50827659 21.72597661 30.60709929 26.49005792 17.54830779 25.79420234
 16.05881895 15.44407281 19.89513254 21.72597661 21.72597661 23.32331968
 25.64042788 28.97548892 24.90532013 14.02746048 43.44101044 21.72597661
 23.32331968 21.72597661 25.43803727 17.82865762 20.30936428 43.05952486
 42.81452885 25.13026738 21.72597661 15.12740478 25.13026738 15.44407281
 18.31561257 15.29151416 25.13026738 28.46532842 23.97120964 23.25907479
 14.02746048 25.13026738 15.44407281 21.72597661 23.25907479 21.72597661
 25.86887978 22.13241693 24.81381208 21.72597661 14.02746048 21.07666906
 23.25907479 23.39001805 29.26856252 14.02746048 15.44407281 16.16543356
 15.44407281 18.47796517 14.02746048 21.72597661 14.02746048 43.73480054
 26.17980062 14.02746048 15.7325048  21.72597661 21.78263112 15.2403543
 32.51335106]

In [27]:
# 모형평가 - MSE
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_te, rf_pred)
print(mse)

27.07190389377867