## 파이캐럿_분류

In [3]:
import pandas as pd
from pycaret.classification import *
df = pd.read_csv('wine_data.csv')

In [4]:
exp1 = setup(data=df, target='class', session_id=123)

In [5]:
best_model = compare_models()

In [7]:
tuned_model = tune_model(best_model)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [8]:
evaluate_model(tuned_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [9]:
final_model = finalize_model(tuned_model)

In [10]:
save_model(final_model, 'wine_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['Alcohol', 'Malic', 'Ash',
                                              'Alcalinity', 'Magesium',
                                              'Phenols', 'Flavanoids',
                                              'Nonflavanoids', 'Proanthocyanins',
                                              'Color', 'Hue', 'Dilution',
                                              'Proline'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               miss...
                  ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0,
                                       class_weight=None, criterion='gini',
                                       max_depth=None, max_features='sqrt',
                                       max_leaf_nodes=None, max_samples=None,
                                       min_impurity_decrease=0.0,
                                       min_samples_leaf=1, min_samples_split=2,
                                       min_weight_fraction_leaf=0.0,
                                       monotonic_cst=None, n_estimators=100,
                                       n_jobs=-1, oob_score=False,
                                       random_state=123, verbose=0,
                                       warm_start=False))],
          verbose=False),
 'wine_model.pkl')

In [11]:
loaded_model = load_model('wine_model')

Transformation Pipeline and Model Successfully Loaded

In [15]:
df.iloc[20:40, 0:-1]

,Alcohol,Malic,Ash,Alcalinity,Magesium,Phenols,Flavanoids,Nonflavanoids,Proanthocyanins,Color,Hue,Dilution,Proline
20,14.06,1.63,2.28,16.0,126,3.00,3.17,0.24,2.10,5.65,1.09,3.71,780
21,12.93,3.80,2.65,18.6,102,2.41,2.41,0.25,1.98,4.50,1.03,3.52,770
22,13.71,1.86,2.36,16.6,101,2.61,2.88,0.27,1.69,3.80,1.11,4.00,1035
23,12.85,1.60,2.52,17.8,95,2.48,2.37,0.26,1.46,3.93,1.09,3.63,1015
24,13.50,1.81,2.61,20.0,96,2.53,2.61,0.28,1.66,3.52,1.12,3.82,845
25,13.05,2.05,3.22,25.0,124,2.63,2.68,0.47,1.92,3.58,1.13,3.20,830
26,13.39,1.77,2.62,16.1,93,2.85,2.94,0.34,1.45,4.80,0.92,3.22,1195
27,13.30,1.72,2.14,17.0,94,2.40,2.19,0.27,1.35,3.95,1.02,2.77,1285
28,13.87,1.90,2.80,19.4,107,2.95,2.97,0.37,1.76,4.50,1.25,3.40,915
29,14.02,1.68,2.21,16.0,96,2.65,2.33,0.26,1.98,4.70,1.04,3.59,1035
30,13.73,1.50,2.70,22.5,101,3.00,3.25,0.29,2.38,5.70,1.19,2.71,1285
31,13.58,1.66,2.36,19.1,106,2.86,3.19,0.22,1.95,6.90,1.09,2.88,1515
32,13.68,1.83,2.36,17.2,104,2.42,2.69,0.42,1.97,3.84,1.23,2.87,990
33,13.76,1.53,2.70,19.5,132,2.95,2.74,0.50,1.35,5.40,1.25,3.00,1235
34,13.51,1.80,2.65,19.0,110,2.35,2.53,0.29,1.54,4.20,1.10,2.87,1095
35,13.48,1.81,2.41,20.5,100,2.70,2.98,0.26,1.86,5.10,1.04,3.47,920
36,13.28,1.64,2.84,15.5,110,2.60,2.68,0.34,1.36,4.60,1.09,2.78,880
37,13.05,1.65,2.55,18.0,98,2.45,2.43,0.29,1.44,4.25,1.12,2.51,1105
38,13.07,1.50,2.10,15.5,98,2.40,2.64,0.28,1.37,3.70,1.18,2.69,1020
39,14.22,3.99,2.51,13.2,128,3.00,3.04,0.20,2.08,5.10,0.89,3.53,760

In [12]:
new_data = df.iloc[20:40, 0:-1]

In [13]:
predictions = predict_model(loaded_model, data=new_data)

In [14]:
predictions

,Alcohol,Malic,Ash,Alcalinity,Magesium,Phenols,Flavanoids,Nonflavanoids,Proanthocyanins,Color,Hue,Dilution,Proline,prediction_label,prediction_score
20,14.06,1.63,2.28,16.000000,126,3.00,3.17,0.24,2.10,5.65,1.09,3.71,780,0,1.0
21,12.93,3.80,2.65,18.600000,102,2.41,2.41,0.25,1.98,4.50,1.03,3.52,770,0,1.0
22,13.71,1.86,2.36,16.600000,101,2.61,2.88,0.27,1.69,3.80,1.11,4.00,1035,0,1.0
23,12.85,1.60,2.52,17.799999,95,2.48,2.37,0.26,1.46,3.93,1.09,3.63,1015,0,1.0
24,13.50,1.81,2.61,20.000000,96,2.53,2.61,0.28,1.66,3.52,1.12,3.82,845,0,1.0
25,13.05,2.05,3.22,25.000000,124,2.63,2.68,0.47,1.92,3.58,1.13,3.20,830,0,1.0
26,13.39,1.77,2.62,16.100000,93,2.85,2.94,0.34,1.45,4.80,0.92,3.22,1195,0,1.0
27,13.30,1.72,2.14,17.000000,94,2.40,2.19,0.27,1.35,3.95,1.02,2.77,1285,0,1.0
28,13.87,1.90,2.80,19.400000,107,2.95,2.97,0.37,1.76,4.50,1.25,3.40,915,0,1.0
29,14.02,1.68,2.21,16.000000,96,2.65,2.33,0.26,1.98,4.70,1.04,3.59,1035,0,1.0
30,13.73,1.50,2.70,22.500000,101,3.00,3.25,0.29,2.38,5.70,1.19,2.71,1285,0,1.0
31,13.58,1.66,2.36,19.100000,106,2.86,3.19,0.22,1.95,6.90,1.09,2.88,1515,0,1.0
32,13.68,1.83,2.36,17.200001,104,2.42,2.69,0.42,1.97,3.84,1.23,2.87,990,0,1.0
33,13.76,1.53,2.70,19.500000,132,2.95,2.74,0.50,1.35,5.40,1.25,3.00,1235,0,1.0
34,13.51,1.80,2.65,19.000000,110,2.35,2.53,0.29,1.54,4.20,1.10,2.87,1095,0,1.0
35,13.48,1.81,2.41,20.500000,100,2.70,2.98,0.26,1.86,5.10,1.04,3.47,920,0,1.0
36,13.28,1.64,2.84,15.500000,110,2.60,2.68,0.34,1.36,4.60,1.09,2.78,880,0,1.0
37,13.05,1.65,2.55,18.000000,98,2.45,2.43,0.29,1.44,4.25,1.12,2.51,1105,0,1.0
38,13.07,1.50,2.10,15.500000,98,2.40,2.64,0.28,1.37,3.70,1.18,2.69,1020,0,1.0
39,14.22,3.99,2.51,13.200000,128,3.00,3.04,0.20,2.08,5.10,0.89,3.53,760,0,1.0