## 파이캐럿_회귀

In [11]:
from pycaret.regression import *

In [12]:
import pandas as pd
df = pd.read_csv('house_prices.csv')
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [14]:
exp_reg = setup(data=df, target='MEDV', session_id=111)

In [15]:
best_model = compare_models()

In [16]:
tuned_model = tune_model (best_model)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [17]:
evaluate_model(tuned_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [18]:
predict_model(tuned_model)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,prediction_label
93,0.02875,28.0,15.04,0,0.4640,6.211,28.900000,3.6659,4,270,18.200001,396.329987,6.21,25.000000,24.688958
223,0.61470,0.0,6.20,0,0.5070,6.618,80.800003,3.2721,8,307,17.400000,396.899994,7.60,30.100000,24.982438
39,0.02763,75.0,2.95,0,0.4280,6.595,21.799999,5.4011,3,252,18.299999,395.630005,4.32,30.799999,29.508598
122,0.09299,0.0,25.65,0,0.5810,5.961,92.900002,2.0869,2,188,19.100000,378.089996,17.93,20.500000,19.458317
203,0.03510,95.0,2.68,0,0.4161,7.853,33.200001,5.1180,4,224,14.700000,392.779999,3.81,48.500000,44.521930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18,0.80271,0.0,8.14,0,0.5380,5.456,36.599998,3.7965,4,307,21.000000,288.989990,11.69,20.200001,17.822152
218,0.11069,0.0,13.89,1,0.5500,5.951,93.800003,2.8893,5,276,16.400000,396.899994,17.92,21.500000,21.223131
45,0.17142,0.0,6.91,0,0.4480,5.682,33.799999,5.1004,3,233,17.900000,396.899994,10.21,19.299999,20.986954
442,5.66637,0.0,18.10,0,0.7400,6.219,100.000000,2.0048,24,666,20.200001,395.690002,16.59,18.400000,17.095257
158,1.34284,0.0,19.58,0,0.6050,6.066,100.000000,1.7573,5,403,14.700000,353.890015,6.43,24.299999,24.477437

In [19]:
final_model = finalize_model (tuned_model)

In [20]:
save_model(final_model, 'boston_house_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['CRIM', 'ZN', 'INDUS', 'CHAS',
                                              'NOX', 'RM', 'AGE', 'DIS', 'RAD',
                                              'TAX', 'PTRATIO', 'B', 'LSTAT'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='mean'))),
                 ('categorical_imputer'...
                                            criterion='friedman_mse', init=None,
                                            learning_rate=0.05,
                                            loss='squared_error', max_depth=11,
                                            max_features='log2',
                                            max_leaf_nodes=None,
                                            min_impurity_decrease=0.02,
                                            min_samples_leaf=1,
                                            min_samples_split=10,
                                            min_weight_fraction_leaf=0.0,
                                            n_estimators=80,
                                            n_iter_no_change=None,
                                            random_state=111, subsample=0.85,
                                            tol=0.0001, validation_fraction=0.1,
                                            verbose=0, warm_start=False))],
          verbose=False),
 'boston_house_model.pkl')

In [21]:
loaded_model = load_model('boston_house_model')

Transformation Pipeline and Model Successfully Loaded

In [22]:
new_data = df.iloc [20:40,0:-1]
predictions = predict_model(loaded_model, data=new_data)

In [23]:
predictions

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,prediction_label
20,1.25179,0.0,8.14,0,0.538,5.570,98.099998,3.7979,4,307,21.000000,376.570007,21.020000,13.520103
21,0.85204,0.0,8.14,0,0.538,5.965,89.199997,4.0123,4,307,21.000000,392.529999,13.830000,18.760977
22,1.23247,0.0,8.14,0,0.538,6.142,91.699997,3.9769,4,307,21.000000,396.899994,18.719999,15.726852
23,0.98843,0.0,8.14,0,0.538,5.813,100.000000,4.0952,4,307,21.000000,394.540009,19.879999,14.624171
24,0.75026,0.0,8.14,0,0.538,5.924,94.099998,4.3996,4,307,21.000000,394.329987,16.299999,15.863861
25,0.84054,0.0,8.14,0,0.538,5.599,85.699997,4.4546,4,307,21.000000,303.420013,16.510000,14.422749
26,0.67191,0.0,8.14,0,0.538,5.813,90.300003,4.6820,4,307,21.000000,376.880005,14.810000,16.675075
27,0.95577,0.0,8.14,0,0.538,6.047,88.800003,4.4534,4,307,21.000000,306.380005,17.280001,14.923028
28,0.77299,0.0,8.14,0,0.538,6.495,94.400002,4.4547,4,307,21.000000,387.940002,12.800000,18.474319
29,1.00245,0.0,8.14,0,0.538,6.674,87.300003,4.2390,4,307,21.000000,380.230011,11.980000,20.683199
30,1.13081,0.0,8.14,0,0.538,5.713,94.099998,4.2330,4,307,21.000000,360.170013,22.600000,13.054731
31,1.35472,0.0,8.14,0,0.538,6.072,100.000000,4.1750,4,307,21.000000,376.730011,13.040000,15.494926
32,1.38799,0.0,8.14,0,0.538,5.950,82.000000,3.9900,4,307,21.000000,232.600006,27.709999,13.686601
33,1.15172,0.0,8.14,0,0.538,5.701,95.000000,3.7872,4,307,21.000000,358.769989,18.350000,13.408484
34,1.61282,0.0,8.14,0,0.538,6.096,96.900002,3.7598,4,307,21.000000,248.309998,20.340000,13.773299
35,0.06417,0.0,5.96,0,0.499,5.933,68.199997,3.3603,5,279,19.200001,396.899994,9.680000,19.657180
36,0.09744,0.0,5.96,0,0.499,5.841,61.400002,3.3779,5,279,19.200001,377.559998,11.410000,20.219792
37,0.08014,0.0,5.96,0,0.499,5.850,41.500000,3.9342,5,279,19.200001,396.899994,8.770000,20.916890
38,0.17505,0.0,5.96,0,0.499,5.966,30.200001,3.8473,5,279,19.200001,393.429993,10.130000,24.005320
39,0.02763,75.0,2.95,0,0.428,6.595,21.799999,5.4011,3,252,18.299999,395.630005,4.320000,30.023941